*** Starting uWSGI 2.0.18 (32bit) on [Thu May 23 12:40:59 2019] ***
compiled with version: 5.4.0 20160609 on 22 May 2019 09:27:26
os: Linux-4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 08:59:42 UTC 2019
nodename: Vip
machine: i686
clock source: unix
detected number of CPU cores: 2
current working directory: /home/pyvip/htzj/htzj
writing pidfile to uwsgi.pid
detected binary path: /home/pyvip/.virtualenvs/py3env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/pyvip/htzj
your processes number limit is 7691
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:43059 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
Set PythonHome to /home/pyvip/.virtualenvs/py3env
Python main interpreter initialized at 0x968dfe0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 358400 bytes (350 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
ImportError: No module named 'htzj.wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
failed to open python file htzj/wsgi.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 1896)
spawned uWSGI worker 1 (pid: 1897, cores: 2)
spawned uWSGI worker 2 (pid: 1898, cores: 2)
spawned uWSGI worker 3 (pid: 1899, cores: 2)
spawned uWSGI worker 4 (pid: 1900, cores: 2)
spawned uWSGI http 1 (pid: 1901)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 1901)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (32bit) on [Thu May 23 14:24:47 2019] ***
compiled with version: 5.4.0 20160609 on 22 May 2019 09:27:26
os: Linux-4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 08:59:42 UTC 2019
nodename: Vip
machine: i686
clock source: unix
detected number of CPU cores: 2
current working directory: /home/pyvip/htzj/htzj
writing pidfile to uwsgi.pid
detected binary path: /home/pyvip/.virtualenvs/py3env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/pyvip/htzj
your processes number limit is 7691
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:38043 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
Set PythonHome to /home/pyvip/.virtualenvs/py3env
Python main interpreter initialized at 0x8764fe0
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 358400 bytes (350 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
ImportError: No module named 'htzj.wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
failed to open python file htzj/wsgi.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2016)
spawned uWSGI worker 1 (pid: 2017, cores: 2)
spawned uWSGI worker 2 (pid: 2018, cores: 2)
spawned uWSGI worker 3 (pid: 2019, cores: 2)
spawned uWSGI worker 4 (pid: 2020, cores: 2)
spawned uWSGI http 1 (pid: 2021)
SIGINT/SIGQUIT received...killing workers...
gateway "uWSGI http 1" has been buried (pid: 2021)
worker 1 buried after 1 seconds
worker 2 buried after 1 seconds
worker 3 buried after 1 seconds
worker 4 buried after 1 seconds
goodbye to uWSGI.
*** Starting uWSGI 2.0.18 (32bit) on [Thu May 23 14:35:31 2019] ***
compiled with version: 5.4.0 20160609 on 22 May 2019 09:27:26
os: Linux-4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 08:59:42 UTC 2019
nodename: Vip
machine: i686
clock source: unix
detected number of CPU cores: 2
current working directory: /home/pyvip/htzj/htzj
writing pidfile to uwsgi.pid
detected binary path: /home/pyvip/.virtualenvs/py3env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/pyvip/htzj
your processes number limit is 7691
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
uWSGI http bound on 127.0.0.1:8000 fd 4
uwsgi socket 0 bound to TCP address 127.0.0.1:39389 (port auto-assigned) fd 3
Python version: 3.5.2 (default, Nov 12 2018, 13:43:14)  [GCC 5.4.0 20160609]
Set PythonHome to /home/pyvip/.virtualenvs/py3env
Python main interpreter initialized at 0x8d64028
python threads support enabled
your server socket listen backlog is limited to 100 connections
your mercy for graceful operations on workers is 60 seconds
mapped 358400 bytes (350 KB) for 8 cores
*** Operational MODE: preforking+threaded ***
ImportError: No module named 'htzj.wsgi'
unable to load app 0 (mountpoint='') (callable not found or import error)
failed to open python file htzj/wsgi.py
unable to load app 0 (mountpoint='') (callable not found or import error)
*** no app loaded. going in full dynamic mode ***
*** uWSGI is running in multiple interpreter mode ***
spawned uWSGI master process (pid: 2047)
spawned uWSGI worker 1 (pid: 2048, cores: 2)
spawned uWSGI worker 2 (pid: 2049, cores: 2)
spawned uWSGI worker 3 (pid: 2050, cores: 2)
spawned uWSGI worker 4 (pid: 2051, cores: 2)
spawned uWSGI http 1 (pid: 2052)
*** Starting uWSGI 2.0.18 (32bit) on [Thu May 23 14:36:09 2019] ***
compiled with version: 5.4.0 20160609 on 22 May 2019 09:27:26
os: Linux-4.4.0-146-generic #172-Ubuntu SMP Wed Apr 3 08:59:42 UTC 2019
nodename: Vip
machine: i686
clock source: unix
detected number of CPU cores: 2
current working directory: /home/pyvip/htzj/htzj
writing pidfile to uwsgi.pid
detected binary path: /home/pyvip/.virtualenvs/py3env/bin/uwsgi
!!! no internal routing support, rebuild with pcre support !!!
chdir() to /home/pyvip/htzj
your processes number limit is 7691
your memory page size is 4096 bytes
detected max file descriptor number: 1024
lock engine: pthread robust mutexes
thunder lock: disabled (you can enable it with --thunder-lock)
probably another instance of uWSGI is running on the same address (127.0.0.1:8000).
bind(): Address already in use [core/socket.c line 769]
